server:
    port: 9001

spring:
    datasource:
        sql-script-encoding: UTF-8
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true

#actuator
management:
    endpoints:
        web:
            exposure:
                include: '*'


 # my configs
app-configs:
    limitDeProduits: 4


# eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9102/eureka/
