app-configs:
    limitDeProduits: 4
server:
    port: 9001
spring:
    datasource:
        sql-script-encoding: UTF-8
    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
management:
    endpoints:
        web:
            exposure:
                include: "*"
